SHELL = cmd.exe

#
# ZDS II Make File - test project, Debug configuration
#
# Generated by: ZDS II - Z8 Encore! Family 4.11.0 (Build 08052301)
#   IDE component: c:4.11:08050501
#   Install Path: C:\Program Files (x86)\ZiLOG\ZDSII_Z8Encore!_4.11.0\
#

RM = del

ZDS = C:\PROGRA~2\ZiLOG\ZDSII_~1.0
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~2\ZiLOG\ZDSII_~1.0\include
# intermediate files directory
WORKDIR = C:\Users\BezHeslaVOLE\Desktop\Zilog\Debug

CC = @$(BIN)\eZ8cc
AS = @$(BIN)\eZ8asm
LD = @$(BIN)\eZ8link
AR = @$(BIN)\eZ8lib

ASFLAGS =  \
-define:_Z8F1621=1 -define:_Z8ENCORE_XP_64XX_SERIES=1  \
-define:_Z8ENCORE_F642X=1 -define:_SIMULATE=1  \
-include:"..;C:\PROGRA~2\ZiLOG\ZDSII_~1.0\include\std;C:\PROGRA~2\ZiLOG\ZDSII_~1.0\include\zilog;C:\PROGRA~2\ZiLOG\ZDSII_~1.0\include\zilog\Z8ENCO~2"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -NOrevaa -cpu:Z8F1621

LDFLAGS = @.\test_Debug.linkcmd
OUTDIR = C:\Users\BezHeslaVOLE\Desktop\Zilog\Debug

build: test

buildall: clean test

relink: deltarget test

deltarget: 
	@if exist $(WORKDIR)\test.lod  \
            $(RM) $(WORKDIR)\test.lod
	@if exist $(WORKDIR)\test.hex  \
            $(RM) $(WORKDIR)\test.hex
	@if exist $(WORKDIR)\test.map  \
            $(RM) $(WORKDIR)\test.map

clean: 
	@if exist $(WORKDIR)\test.lod  \
            $(RM) $(WORKDIR)\test.lod
	@if exist $(WORKDIR)\test.hex  \
            $(RM) $(WORKDIR)\test.hex
	@if exist $(WORKDIR)\test.map  \
            $(RM) $(WORKDIR)\test.map
	@if exist $(WORKDIR)\IDE1_asm.obj  \
            $(RM) $(WORKDIR)\IDE1_asm.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\IDE1_asm.obj

test: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\IDE1_asm.obj :  \
            C:\Users\BezHeslaVOLE\Desktop\Zilog\IDE1_asm.s  \
            $(INCLUDE)\zilog\ez8dev.inc  \
            $(INCLUDE)\zilog\ez8.inc
	 $(AS) $(ASFLAGS) C:\Users\BEZHES~1\Desktop\Zilog\IDE1_asm.s

